#server:
#  port: 9000
#
#
#spring:
#  #链路追踪
#  zipkin:
#    base-url: http://192.168.200.100:9411/
#    sender:
#      type: web
#      #数据库
#  datasource:
#    url: jdbc:mysql://192.168.200.100:3306/gmall_product?useSSl=false&characterEncoding=utf8
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 7001




# 自定义配置
#app:
#  minio:
#    endpoint: http://192.168.200.100:9000
#    accessKey: admin
#    secretKey: admin123456
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    #链路追踪
  zipkin:
    base-url: http://192.168.200.100:9411/
    sender:
     type: web
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
#    bucketName: gmall